services:
  - type: web
    name: brain-arvr-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 